<a href="https://colab.research.google.com/github/semaozkir/Intro-to-AI/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

In [ ]:
import numpy as np

In [ ]:
# numpy array olustur
# liste = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
dizi = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
dizi

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
# array boyutu
dizi.shape # (15,) -> 15x1 lik bir vektor

(15,)

In [ ]:
# 15x1 lik bir arrayi 3x5 lik bir matrise cevirelim
dizi2 = dizi.reshape(3,5)
dizi2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
print("shape: ", dizi2.shape)
print("dimension: ", dizi2.ndim)
print("size: ",dizi2.size)
print("type: ", type(dizi2))

shape:  (3, 5)
dimension:  2
size:  15
type:  <class 'numpy.ndarray'>


In [ ]:
dizi2D = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,5]])
dizi2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 5]])

In [ ]:
# sifirlardan olusan bir array olusturalim
sifir_dizi = np.zeros((3,4))
sifir_dizi

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# birlerden olsan array
bir_dizi = np.ones((3,4))
bir_dizi

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# bos bir array olustur
bos_dizi = np.empty((2,4))
bos_dizi

array([[4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323],
       [2.5e-323, 3.0e-323, 3.5e-323, 4.0e-323]])

In [ ]:
# arange(x,y,basamak) x den baslar y ye (y dahil degil) kadar gider basamak buyuklugunder artarak ilerler
# 10, 50, basamak = 5
dizi_aralik = np.arange(10,50,8)
dizi_aralik

array([10, 18, 26, 34, 42])

In [ ]:
# linspace  (x,y,basamak) x ve y(dahil) araliginde basamak kadar sayiya boler
dizi_bosluk = np.linspace(10,50,103)
len(dizi_bosluk)

103

**Numpy Temel Operasyonları**

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
print("Toplama: ", a+b)
print("Cikarma: ", a-b)
print("Dizinin kendisi ile carpimi: ", a**2)

Toplama:  [5 7 9]
Cikarma:  [-3 -3 -3]
Dizinin kendisi ile carpimi:  [1 4 9]


In [ ]:
# filtreleme
a = np.array([1,2,3])
filtre = a < 2 # a array'nin icerisinde bulunan 2 den kucuk degerleri goster
filtre

array([ True, False, False])

In [ ]:
# matris carpimi
a = np.array([1,2,3])
b = np.array([4,5,6])
a.dot(b)

32

In [ ]:
a = np.array([[1,2,3],[4,5,6]]) # 2x3
b = np.array([[4,5,6],[1,2,3]]) # 2x3 ->T-> 3x2
a.dot(b.T)

array([[32, 14],
       [77, 32]])

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])
print(sum(a))
print(np.sum(a))

[5 7 9]
21


In [ ]:
print(a.max())
print(np.max(a))

6
6


In [ ]:
print(a.min())
print(np.min(a))

1
1


In [ ]:
# satir satir toplama
a.sum(axis = 1)

array([ 6, 15])

In [ ]:
# sutun sutun toplama
a.sum(axis = 0)

array([5, 7, 9])

In [ ]:
# kare koku
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
# karesi
print(np.square(a))
print(a**2)

[[ 1  4  9]
 [16 25 36]]
[[ 1  4  9]
 [16 25 36]]


In [ ]:
# np.random.rand(3,3)

array([[0.5822582 , 0.29735764, 0.63158337],
       [0.66748743, 0.6383029 , 0.75614163],
       [0.01453915, 0.8746818 , 0.20900089]])

In [ ]:
# rastgele sayi uretme
rastgele_dizi = np.random.random((3,3)) # normal dagilima gore 0-1
rastgele_dizi

array([[0.74866377, 0.73694308, 0.21837979],
       [0.05543257, 0.84625597, 0.89775615],
       [0.50266118, 0.60195258, 0.46735577]])

In [ ]:
rastgele_dizi = np.random.normal(0 ,1 , (5,3)) # normal dagilima 0 ortalamali 1 std, 5 adet deger uret
rastgele_dizi

array([[-0.90958706, -1.59039181,  0.45389321],
       [-0.64904909,  1.00948484, -0.72535123],
       [-0.82941173, -1.88243567,  0.08195165],
       [ 0.72747334,  1.43820674, -0.73074887],
       [ 0.47029311,  0.61648715, -0.14237632]])

**indeksleme ve slicing**

In [ ]:
import numpy as np

In [ ]:
dizi= np.array([1,2,3,4,5,6,7])
dizi[3]

4

In [ ]:
dizi[0:4]

array([1, 2, 3, 4])

In [ ]:
dizi[:4]

array([1, 2, 3, 4])

In [ ]:
dizi[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [ ]:
dizi2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
dizi2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
dizi2D[1,2]

8

In [ ]:
dizi2D[1, :] # : = hepsi sutun kismina yazdigim icin tum sutunlar demek

array([ 6,  7,  8,  9, 10])

In [ ]:
dizi2D[:, 2] #  : = hepsi satir kismina yazdigim icin tum satirlar demek

array([3, 8])

In [ ]:
dizi2D[ 0, 0:2] # 1,  2

array([1, 2])

In [ ]:
dizi2D[:, 2:4]
"""
[ 1,  2,  3,  4,  5],
[ 6,  7,  8,  9, 10]
"""

array([[3, 4],
       [8, 9]])

In [ ]:
dizi2D[-1, :]

array([ 6,  7,  8,  9, 10])

In [ ]:
dizi2D[[0,1], [1,3]]

array([2, 9])

**shape manipulation**

In [ ]:
import numpy as np